[[pages]]
path = "Inicio.py"
name = ""

[[pages]]
name = "Ganado"
is_section = true
icon = ""

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = "📊"

[[pages]]
path = "Produccion.py"
name = "Producción"
icon = "🛄"

[[pages]]
name = "Entidades"
is_section = true
icon = ""

[[pages]]
path = "Entidades.py"
name = "Instituciones"
icon = "📍"

[[pages]]
name = "Acerca de"
is_section = true
icon = ""

[[pages]]
path = "Metodología.py"
name = "Metodología"
icon = "ℹ️"

url_path = "DataPecuario"