[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "🏠"

[[pages]]
path = "Existencia.py"
name = "Existencia Ganado"
icon = "🐾"

[[pages]]
path = "Nacimientos_Muertes.py"
name = "Nacimientos/Muertes"
icon = ":restroom:"

[[pages]]
path = "Leche.py"
name = "Producción de leche"
icon = ":glass_of_milk:"

[[pages]]
path = "Ordenno.py"
name = "Ganado de Ordeño"
icon = "🐮"

[[pages]]
path = "Huevos.py"
name = "Producción avícola"
icon = "🐔"

[[pages]]
path = "Rendimiento_Produccion.py"
name = "Rendimiento Produccion"
icon = ":tractor:"



[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "🧰"

url_path = "DataPecuario"