[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "🏠"

[[pages]]
name = "Ganado"
icon = "🐾"
is_section = true

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = ":hearts:"

[[pages]]
path = "Nacimientos_Muertes.py"
name = "Nacimientos/Muertes"
icon = ":restroom:"

[[pages]]
name = "Producción"
icon = "🏭"
is_section = true

[[pages]]
path = "Leche.py"
name = "Producción de leche"
icon = ":glass_of_milk:"

[[pages]]
path = "Ordenno.py"
name = "Ganado de Ordeño"
icon = "🐮"

[[pages]]
path = "Huevos.py"
name = "Producción de huevos"
icon = "🥚"

[[pages]]
path = "Rendimiento_Produccion.py"
name = "Rendimiento"
icon = ":tractor:"

[[pages]]
name = "Info"
icon = ":information_source:"
is_section = true

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "🧰"

url_path = "DataPecuario"