[[pages]]
path = "pages/Inicio.py"
name = "DataPecuario"
icon = "🏠"

[[pages]]
name = "Ganado"
is_section = true
icon = ""

[[pages]]
path = "pages/Existencia.py"
name = "Existencia"
icon = "♥️"

[[pages]]
path = "pages/Produccion.py"
name = "Producción"
icon = "🏭"

[[pages]]
name = "Entidades"
is_section = true
icon = ""

[[pages]]
path = "pages/Entidades.py"
name = "Instituciones"
icon = "📍"

[[pages]]
name = "Acerca de"
is_section = true
icon = ""

[[pages]]
path = "pages/Metodologia.py"
name = "Metodologia"
icon = "ℹ️"

url_path = "DataPecuario"