[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "🏠"

[[pages]]
path = "Existencia.py"
name = "Existencia del ganado"
icon = "🐾"

[[pages]]
path = "Leche.py"
name = "Producción ganadera"
icon = "🏭"

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "🧰"

url_path = "DataPecuario"