[[pages]]
path = "Inicio.py"
name = "Inicio"
icon = "🏠"

[[pages]]
path = "Existencia.py"
name = "Existencia"
icon = "🐾"

[[pages]]
path = "Leche.py"
name = "Producción"
icon = "🏭"

[[pages]]
path = "Metodologia.py"
name = "Metodologia"
icon = "🧰"

url_path = "DataPecuario"